
package io.sample.mnms.irritatedtown.soapclient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "InMemoryPersonServiceService", targetNamespace = "http://services.soap.services.irritatedtown.mnms.sample.io/", wsdlLocation = "file:/home/mehdi/Documents/tests/java/simples-eip-services/common-client/src/main/resources/wsdl/persons.service.wsdl")
public class InMemoryPersonServiceService
    extends Service
{

    private static final URL INMEMORYPERSONSERVICESERVICE_WSDL_LOCATION;
    private static final WebServiceException INMEMORYPERSONSERVICESERVICE_EXCEPTION;
    private static final QName INMEMORYPERSONSERVICESERVICE_QNAME = new QName("http://services.soap.services.irritatedtown.mnms.sample.io/", "InMemoryPersonServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/mehdi/Documents/tests/java/simples-eip-services/common-client/src/main/resources/wsdl/persons.service.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INMEMORYPERSONSERVICESERVICE_WSDL_LOCATION = url;
        INMEMORYPERSONSERVICESERVICE_EXCEPTION = e;
    }

    public InMemoryPersonServiceService() {
        super(__getWsdlLocation(), INMEMORYPERSONSERVICESERVICE_QNAME);
    }

    public InMemoryPersonServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), INMEMORYPERSONSERVICESERVICE_QNAME, features);
    }

    public InMemoryPersonServiceService(URL wsdlLocation) {
        super(wsdlLocation, INMEMORYPERSONSERVICESERVICE_QNAME);
    }

    public InMemoryPersonServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INMEMORYPERSONSERVICESERVICE_QNAME, features);
    }

    public InMemoryPersonServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InMemoryPersonServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PersonInformation
     */
    @WebEndpoint(name = "InMemoryPersonServicePort")
    public PersonInformation getInMemoryPersonServicePort() {
        return super.getPort(new QName("http://services.soap.services.irritatedtown.mnms.sample.io/", "InMemoryPersonServicePort"), PersonInformation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PersonInformation
     */
    @WebEndpoint(name = "InMemoryPersonServicePort")
    public PersonInformation getInMemoryPersonServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://services.soap.services.irritatedtown.mnms.sample.io/", "InMemoryPersonServicePort"), PersonInformation.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INMEMORYPERSONSERVICESERVICE_EXCEPTION!= null) {
            throw INMEMORYPERSONSERVICESERVICE_EXCEPTION;
        }
        return INMEMORYPERSONSERVICESERVICE_WSDL_LOCATION;
    }

}
