
package io.sample.mnms.irritatedtown.soapclient;

import java.util.List;
import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.xml.bind.annotation.XmlSeeAlso;
import jakarta.xml.ws.RequestWrapper;
import jakarta.xml.ws.ResponseWrapper;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "PersonInformation", targetNamespace = "http://sample.service.io/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PersonInformation {


    /**
     * 
     * @return
     *     returns java.util.List<io.sample.mnms.irritatedtown.soapclient.Person>
     */
    @WebMethod(action = "urn:personsInformation")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "fetchPersons", targetNamespace = "http://sample.service.io", className = "io.sample.mnms.irritatedtown.soapclient.FetchPersons")
    @ResponseWrapper(localName = "fetchPersonsResponse", targetNamespace = "http://sample.service.io", className = "io.sample.mnms.irritatedtown.soapclient.FetchPersonsResponse")
    public List<Person> fetchPersons();

    /**
     * 
     * @param personId
     * @return
     *     returns io.sample.mnms.irritatedtown.soapclient.Person
     */
    @WebMethod(action = "urn:personInformation")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findById", targetNamespace = "http://sample.service.io", className = "io.sample.mnms.irritatedtown.soapclient.FindById")
    @ResponseWrapper(localName = "findByIdResponse", targetNamespace = "http://sample.service.io", className = "io.sample.mnms.irritatedtown.soapclient.FindByIdResponse")
    public Person findById(
        @WebParam(name = "personId", targetNamespace = "")
        String personId);

}
