# The last version of the open api is 3.1.0
openapi: 3.0.3
info:
  title: GCFacade REST API
  description: |-
    This is a excerpt of our API
  termsOfService: http://groupet2i.com/apis/tos.html
  contact:
    email: miga@groupe-t2i.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 0.0.1
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://localhost:8081/rest
    description: development server url
tags:
  - name: persons
    description: Read person information from the person directory.
    externalDocs:
      description: Find out more
      url: http://docs.groupet2i.com/apis/gc-facade-rest-api
paths:
  /rest/persons:
    get:
      tags:
        - persons
      summary: fetch all persons from the registry
      description: |-
        According to filters passed to the API, the system will fetch a return the
        list of persons matching search criteria.
      parameters:
        - $ref: '#/components/parameters/api_key'
        - name: Content-Type
          in: header
          description: the content type of the request
          required: true
          schema:
            type: string
        - name: Accept
          in: header
          description: the content type accepted by the client
          required: true
          schema:
            type: string
        - name: q
          in: query
          description: the optional search query in an url encoded LUCENE query format
          required: false
          schema:
            type: string
      responses:
        200:
          description: The list of the persons
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PhysicalPersons'
        400:
          description: Error during processing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        # TODO: add security error (401, 403)
        415:
          description: Provided Media type is not supported
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        500:
          description: Internal error during processing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - persons_auth:
            - read:persons
        - api_key: []

  /rest/persons/{personId}:
    get:
      tags:
        - persons
      summary: fetch information about a person in the service.
      description: |-
        Fetch all information about a person from the service and return those in a
        special DTO.
      parameters:
        - $ref: '#/components/parameters/api_key'
        - name: Content-Type
          in: header
          description: the content type of the request
          required: true
          schema:
            type: string
        - name: Accept
          in: header
          description: the content type accepted by the client
          required: true
          schema:
            type: string
        - name: personId
          in: path
          description: the unique id of the person to fetch information for.
          required: true
          schema:
            type: string
      responses:
        200:
          description: The person find in the repository.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PhysicalPerson'
        400:
          description: Error during processing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        404:
          description: The person does not exists in the registry.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        # TODO: add security error (401, 403)
        415:
          description: Provided Media type is not supported
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
        500:
          description: Internal error during processing
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ApiResponse'
      security:
        - persons_auth:
            - read:persons
        - api_key: []

components:
  parameters:
    api_key:
      name: api_key
      in: header
      description: ''
      required: false
      schema:
        type: string
  schemas:

    PhysicalPerson:
      description: Representation of a physical person.
      type: object
      properties:
        id:
          type: string
        email:
          type: string
          format: email
        firstName:
          type: string
        lastName:
          type: string

    PhysicalPersons:
      description: Representation of a list of physical person with array prototype poisoning kind of protection.
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/PhysicalPerson'

    ApiResponse:
      type: object
      properties:
        code:
          type: integer
          format: int32
        type:
          type: string
        message:
          type: string
      xml:
        name: '##default'

  securitySchemes:
    persons_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: https://petstore3.swagger.io/oauth/authorize
          scopes:
            read:persons: read information about persons
    api_key:
      type: apiKey
      name: api_key
      in: header
